### ISSUE TITLE
pushDockerImage should throw an exception if no tags are specified

### ISSUE THREAD

**Issue by kerkhofsd** [xenit-eu/alfresco-docker-gradle-plugin#114]
Steps to reproduce:
- don't specify any tags in e.g. the `dockerAlfresco.dockerBuild` configuration

AS-IS Behavior:
- `pushDockerImage` task succeeds, but doesn't actually publish the docker image
- plugin users need to spend time investigating what is wrong. 

> Task :pushDockerImage
Caching disabled for task ':pushDockerImage' because:
  Build cache is disabled
Task ':pushDockerImage' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
:pushDockerImage (Thread[Execution worker for ':' Thread 3,5,main]) completed. Took 0.009 secs.

TO-BE behavior:
- `pushDockerImage` should trow an exception if no tags are specified

Remark:
An issue since 5.x, where `automaticTags` defaults to false.

**Comment by vierbergenlars** [comment]
`pushDockerImage` should throw an exception when it has no work to be done.

If you _want_ to not use any tags, and only use the image for testing locally, you won't use `pushDockerImage`, and there will be no problem.
