### ISSUE TITLE
dockerCompose.fromProject() with user-configured environment variable

### ISSUE THREAD

**Issue by vierbergenlars** [xenit-eu/alfresco-docker-gradle-plugin#170]
# The problem
Currently, `dockerCompose.fromProject()` only supports passing the project to load docker images from, and it automatically derives the name of the environment variable from those.

I have already seen too many people (including myself) trying to work around this restriction by using ugly hacks like

```groovy
project.evaluationDependsOn(":otherproject")
def otherProject = project(":otherproject");
dockerCompose {
  fromBuildImage("MY_ENVVAR", otherProject.tasks.named("buildDockerImage"))
}
```

This approach has multiple pitfalls:

1. forgetting `evaluationDependsOn()`, which will result in the build working only sometimes (although consistently) based on the order in which projects are evaluated. Otherwise they encounter a strange error like `Task with name 'buildDockerImage' not found in project ':otherproject'`
2. Being puzzled by a strange error `No such property: tasks for class: eu.xenit.gradle.docker.compose.DockerComposeSettingsOverride` when using `project()` directly inside `dockerCompose` instead of using a variable. (This happens because `dockerCompose` grabs all function calls to make sub-configurations)
3. When using cross-configuration, the solution above does not hold, because other projects may also need to be evaluated to configure `:otherproject` correctly.

# Proposed solution

Make it possible to optionally add an environment variable to `dockerCompose.fromProject()`, in the same way as `dockerCompose.fromBuildImage()` works.

Of course, this will only work when the project only has a single `DockerBuildImage` task, as we can't assign the same environment name to multiple tasks. To fix this, we will follow the same rules as we are currently using to register docker image IDs to project names. Instead of the prefix from the project name and a `_DOCKER_IMAGE` suffix, we will use the provided environment variable name as a prefix and use no suffix.

## Single-task case

```groovy
dockerCompose {
   fromProject("MY_ENVVAR", ":otherproject")
}
```

1. Assigns the image ID from `:otherproject:buildDockerImage` to `MY_ENVVAR`

## Multiple tasks case

```groovy
dockerCompose {
   fromProject("MY_ENVVAR", ":otherproject")
}
```

1. Assigns the image ID from `:otherproject:buildDockerImage` to `MY_ENVVAR`
2. Assigns the image IDs from `:otherproject:${taskName}` to `MY_ENVVAR_${TASK_NAME}`

**Comment by WimCrols** [comment]
Many of my team's projects have multiple `buildDockerImage` tasks actually. To make them all work in the docker-compose, I see code such as:
```
composeUp {
    dependsOn ':business-api:buildDockerImage'
    dependsOn ':ecm-platform-docker:buildDockerImage'
    dependsOn ':inflow:buildDockerImage'
    doFirst {
        def imageBusinessApi = project(':business-api').buildDockerImage.getImageId().get()
        def imagePlatform = project(':ecm-platform-docker').buildDockerImage.getImageId().get()
        def imageInflow = project(':inflow').buildDockerImage.getImageId().get()
        dockerCompose.environment.put 'ECM_BUSINESS_API_DOCKER_IMAGE', imageBusinessApi
        dockerCompose.environment.put 'ECM_PLATFORM_DOCKER_IMAGE', imagePlatform
        dockerCompose.environment.put 'ECM_INFLOW_DOCKER_IMAGE', imageInflow
    }
}
``` 
Since this type of deployment will become more common in the future, I think an enhancement that supports that would be widely used.

**Comment by WimCrols** [comment]
Wait... did I misinterpret your comment _"this will only work when the project only has a single DockerBuildImage task"_? Because your last example does seem to work for the above use-case.

**Comment by vierbergenlars** [comment]
> Wait... did I misinterpret your comment "this will only work when the project only has a single DockerBuildImage task"? Because your last example does seem to work for the above use-case.

I think so, because the single DockerBuildImage task refers to a single task within one gradle project. My last example does work for the case where there is more than a single DockerBuildImage task, but its workings might also be a bit confusing
