### ISSUE TITLE
DOCKER_TLS_VERIFY=0 is hardcoded

### ISSUE THREAD

**Issue by tgeens** [xenit-eu/alfresco-docker-gradle-plugin#19]
Is there a reason why we are enforcing `DOCKER_TLS_VERIFY=0` ?

1. It's not secure, while it could be
2. On recent installations this results in huge amounts of warnings, below on stderr

```
/tmp/_MEIwiUF1J/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
```

**Comment by thijslemmens** [comment]
I think this is just a leftover. This hard coding should be removed.
