### ISSUE TITLE
Task ":composeUp" fails when the docker-compose cmd prints warnings on stderr

### ISSUE THREAD

**Issue by tgeens** [xenit-eu/alfresco-docker-gradle-plugin#20]
Why does it fail with warnings on _stderr_:  
* upstream issue https://github.com/avast/gradle-docker-compose-plugin/issues/171 fixed in 0.8.9 (current release is 0.8.12)

Why could there be _WARNINGS_ printed on _stderr_:
* If docker-compose.yml references an unset env variable
* When you try to use this plugin with a TLS-protected docker daemon, you run into issue https://github.com/xenit-eu/alfresco-docker-gradle-plugin/issues/19

**Comment by vierbergenlars** [comment]
Fixed in #21
