### ISSUE TITLE
$DOCKER_IMAGE is not available in nested compose-configurations

### ISSUE THREAD

**Issue by tgeens** [xenit-eu/alfresco-docker-gradle-plugin#24]
This plugin supports docker-compose tasks through this plugin: https://github.com/avast/gradle-docker-compose-plugin

`$DOCKER_IMAGE` variable is automatically available in the root `composeXXX`-tasks, but not in the nested configurations (https://github.com/avast/gradle-docker-compose-plugin#nested-configurations)

Use case: very useful to run integration-tests against different configurations/compose-files with the same docker-image

**Comment by vierbergenlars** [comment]
Superseded by #59
