### ISSUE TITLE
Make `compose*` tasks disableable

### ISSUE THREAD

**Issue by vierbergenlars** [xenit-eu/alfresco-docker-gradle-plugin#26]
Currently, the `composeUp`, `composeDown`, etc. tasks are always created.

It would be nice to be able to disable these tasks in, for example, a subproject that only builds a docker image, but does not handle docker-compose.

**Comment by thijslemmens** [comment]
You can just "not use" the task.

**Comment by vierbergenlars** [comment]
That breaks quite ugly when doing a shortcut `./gradlew composeUp`, because it can't find an non-existing `docker-compose.yml` file

**Comment by thijslemmens** [comment]
Then we should give a clear error message in that case.

**Comment by tgeens** [comment]
That's also pretty annoying if you have multiple subprojects building
docker images, but only subproject has a *compose* file. You can no longer
to ./gradlew composeUp - but you need to type out the subprojects name
every time.

I'm in favor of disabling the task-creating :-)

Met vriendelijke groeten,

Toon Geens

**Comment by vierbergenlars** [comment]
You can disable the compose tasks by using
```groovy
tasks.configureEach {
   if(it.name.startsWith('compose')) {
      it.enabled = false
   }
}
```
or by writing it out just for the tasks you want to disable

```groovy
composeUp.enabled = false
composeDown.enabled = false
```
