### ISSUE TITLE
Make it possible to easily clean up images that are built during buildDockerImage

### ISSUE THREAD

**Issue by vierbergenlars** [xenit-eu/alfresco-docker-gradle-plugin#46]
When a docker image is built by the plugin, the image stays on the system, even after it has been pushed to docker hub or after it has been used to composeUp.
Especially on build servers, this can be a problem, because old images that are not used anywhere anymore build up and are not automatically removed.

Maybe the plugin can help by offering a task to remove the image it has built.
For this to work, it probably has to save the image ID that it built somewhere

**Comment by thijslemmens** [comment]
won't do
