### ISSUE TITLE
Plugin doesn't use the docker credentials store

### ISSUE THREAD

**Issue by rschev** [xenit-eu/alfresco-docker-gradle-plugin#65]
Docker has [credentials store helpers](https://docs.docker.com/engine/reference/commandline/login/#credentials-store) for storing the data from `docker login` in a secure fashion. This plugin, however, uses `eu.xenit.docker.registry.username` and `eu.xenit.docker.registry.password` in the gradle.properties file as plaintext. When those are missing, it doesn't prompt the D-Bus Secret Service to ask me for my password.

I can circumvent this by just running `docker pull $image` every time I get the error, after which the plugin uses the locally-cached image, but obviously it would be neater if I was correctly prompted for my keyring password instead.

**Comment by tgeens** [comment]
Related upstream-upstream issue: https://github.com/docker-java/docker-java/issues/1048

**Comment by vierbergenlars** [comment]
Fixed upstream https://github.com/bmuschko/gradle-docker-plugin/issues/743

**Comment by vierbergenlars** [comment]
This is now a duplicate of #55

**Comment by vierbergenlars** [comment]
Duplicate of #55
